### ISSUE TITLE
新版本QQ中CheckVideoMsg函数原型发生变化且MinHook报MH_ERROR_NOT_EXECUTABLE错误，无法hook

### ISSUE THREAD

**Issue by spianmo** [bstaint/MsgIPC#1]
新老QQCheckVideoMsg函数原型变化
```
void __cdecl Util::Msg::CheckVideoMsg(int,unsigned long,unsigned long,struct ITXMsgPack *)
void __cdecl Util::Msg::CheckVideoMsg(int, unsigned int, unsigned int, unsigned int, struct ITXMsgPack *)
```
替换QQ进程中的CheckVideoMsg函数时MinHook报MH_CreateHook failed, MH_STATUS = MH_ERROR_NOT_EXECUTABLE；是否有可能是因为QQ启动了内存保护（Q盾）？是否可以通过VirtualProtect修改QQ的内存保护级别？经我尝试VirtualProtect无效，是否还有其他办法解决这一问题？

**Comment by spianmo** [comment]
PCQQ的v8.2.17720版本太老了，2016.3发布的，目前连都登录都登录不上了

**Comment by bstaint** [comment]
可以登录吧，我一直用，不过是我用的修改版，如果hook失败的话应该是驱动层保护问题，可以搜下有没有去保护补丁，我一会试试新版。

**Comment by spianmo** [comment]
谢谢，已watched，持续关注

**Comment by bstaint** [comment]
已经测试了，更新了下代码加了点输出，确保两点：
1. 确保关闭QQProtect进程（https://www.lanzous.com/i8findc）, 补丁网上找的，注意安全问题。
2. KernelUtil.dll中CheckVideoMsg导出符号是否一致。
https://github.com/bstaint/MsgIPC/blob/a49c5c1ed5747d6fe7a86e291efe080e3c7f8e49/dll/qqdef.h#L9

**Comment by spianmo** [comment]
> 已经测试了，更新了下代码加了点输出，确保两点：
> 
> 1. 确保关闭QQProtect进程（[https://www.lanzous.com/i8findc）](https://www.lanzous.com/i8findc%EF%BC%89), 补丁网上找的，注意安全问题。
> 2. KernelUtil.dll中CheckVideoMsg导出符号是否一致。
>    https://github.com/bstaint/MsgIPC/blob/a49c5c1ed5747d6fe7a86e291efe080e3c7f8e49/dll/qqdef.h#L9

感谢，我试试
